### ISSUE TITLE
Is this in active development?

### ISSUE THREAD

**Issue by prscX** [taxfix/native-navigation#40]
Hi @taxfixer,

I am planning to migrate navigation to Airbnb/native-navigation but I don't think that is in active development. Due to their internal priorities they have kept development on hold

Is this fork in active development? Are you using it in production?

I am looking to use this fork for my app, is it feasible to use the same?

Thanks
Pranav

**Comment by notjosh** [comment]
Hiya,

> Is this fork in active development?

Yup, the `develop` branch is reasonably active. But occasionally we'll set some defaults to values that make sense for us, without exposing them as configuration.

> Are you using it in production?

Not yet, but we're planning our first release this week on Android, with iOS coming up shortly. The team seems fairly keen on moving to something else though (with longer term support), so I don't know how long we'll keep it in production.

> I am looking to use this fork for my app, is it feasible to use the same?

It should be reasonably stable, yeah. It certainly resolves some quirky showstoppers from the original repo. I just can't promise it will be maintained into the future.

**Comment by prscX** [comment]
Thanks @notjosh for the detailed response

Good to hear that their is some development on airbnb/native-navigation. I personally feel that it has great potential of becoming a single solution for RN Native Navigation, but looking to its current state not sure whether it right time to adopt this solution or not

>The team seems fairly keen on moving to something else though (with longer term support)

Any thoughts on which solution your team is looking for the migration

Thanks
Pranav

**Comment by notjosh** [comment]
> Any thoughts on which solution your team is looking for the migration

The team seems pretty keen on [wix/react-native-navigation](https://github.com/wix/react-native-navigation/tree/v2) which seems to be coming along okay. Different features and different compromises but ultimately does about the same job.

**Comment by prscX** [comment]
Thanks @notjosh for response

Thanks
Pranav

**Comment by seanlau555** [comment]
Hi @notjosh,

I am also willing to try this fork. Are there any example about how you guys make public view, tab navigator and stack navigator? It will be great if you can share with us. By looking the example in native-navigation, it seems that we need a lot native code and I am not a android expert. 

I have already downloaded the taxfix iOS version. It looks and works great! And, I am looking forward to the android one.

Also, I would like to thanks @prscX referencing this for me.

Best Regards,
Sean

**Comment by notjosh** [comment]
The example code is mostly identical to the Airbnb sample project. But we're not doing any of that set up in our app (though, we _do_ have some native code for presenting some custom root views, because of differences across platforms).

I don't know if we'll spend much time making the examples significantly better though - we're not actively maintaining this as an OSS product (for now?), but instead just open-sourcing our bugfixes/changes/etc.

**Comment by seanlau555** [comment]
@notjosh Thank you so much!
